apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cadvisor
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
