apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: NodePort
  selector:
    app: store-admin
  ports:
    - port: 8081        # container listens on 8081
      targetPort: 8081
      nodePort: 30081   # NodePort (browser will use this)
