apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
    istio: proxy
    security.istio.io/tlsMode: istio
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002

    - name: http-envoy-prom
      port: 15090
      targetPort: 15090
